"bhop_1n5an3"
{
   "name" "bhop_1n5an3"
   "t_arms" ""
   "ct_arms" ""
   "t_models"
   {
      "tm_anarchist" ""
      "tm_anarchist_variantA" ""
      "tm_anarchist_variantB" ""
      "tm_anarchist_variantC" ""
      "tm_anarchist_variantD" ""
   }
   "ct_models"
   {
      "tm_anarchist" ""
      "tm_anarchist_variantA" ""
      "tm_anarchist_variantB" ""
      "tm_anarchist_variantC" ""
      "tm_anarchist_variantD" ""
   }
}

